import test from 'node:test';
import assert from 'node:assert/strict';
import {reportAction,validateReport} from '../supabase/functions/step-publicity-report-runtime-v1/report-core.mjs';
const id='e597c70f-bc79-436f-87ed-762b6652d07e',mutationId='004008d8-e14e-4692-b123-d59f8a5c13bf';
const input={action:'save',id,mutationId,revision:0,campus:'神領校',category:'良い事・頑張り',title:'動作確認',body:'教室の報告',eventDate:'2026-10-07',externalUse:false,authorName:'テスト',token:'valid'};
function setup(actor={code:'test-a',level:1}){const rows=[];let count=0;const deps={now:()=>new Date(1791324000000+(count++)*1000).toISOString(),verify:async token=>{if(token!=='valid')throw Object.assign(new Error('Unauthorized'),{status:401});return actor;},authorize:async()=> 'all',verifyReader:async k=>{if(k!=='reader')throw Object.assign(new Error('Unauthorized'),{status:401});},pg:async(path,opt={})=>{const url=new URL('https://test/'+path),p=url.searchParams;let found=rows.filter(r=>(!p.has('id')||r.id===p.get('id').slice(3))&&(!p.has('author_code')||r.author_code===p.get('author_code').slice(3))&&(!p.has('revision')||r.revision===Number(p.get('revision').slice(3))));if(opt.method==='POST'){const row=JSON.parse(opt.body);if(rows.some(r=>r.id===row.id))return [];rows.push(row);return [structuredClone(row)];}if(opt.method==='PATCH'){if(!found.length)return [];Object.assign(found[0],JSON.parse(opt.body));return [structuredClone(found[0])];}const offset=Number(p.get('offset')||0);return structuredClone(found.slice(offset,offset+Number(p.get('limit')||100)));}};return{rows,deps};}
test('signed-in reporter saves with server actor identity and defaults',async()=>{const{rows,deps}=setup();const r=await reportAction({...input,author_code:'forged'},deps);assert.equal(r.report.author_code,'test-a');assert.equal(rows.length,1);assert.equal(r.report.external_use,false);});
test('missing or invalid staff session cannot save',async()=>{const{rows,deps}=setup();await assert.rejects(reportAction({...input,token:''},deps),e=>e.status===401);assert.equal(rows.length,0);});
test('list returns only own reports except owner level 4',async()=>{const{rows,deps}=setup();rows.push({id,author_code:'test-a'},{id:crypto.randomUUID(),author_code:'test-b'});assert.equal((await reportAction({action:'list',token:'valid'},deps)).reports.length,1);const owner={...deps,verify:async()=>({code:'owner',level:4})};assert.equal((await reportAction({action:'list',token:'valid'},owner)).reports.length,2);});
test('another reporter cannot edit a report or infer it from a successful response',async()=>{const{rows,deps}=setup();await reportAction(input,deps);const other={...deps,verify:async()=>({code:'test-b',level:1})};await assert.rejects(reportAction({...input,revision:1,mutationId:crypto.randomUUID(),body:'forged'},other),e=>e.status===403);assert.equal(rows[0].body,input.body);});
test('owner can edit without changing original author',async()=>{const{rows,deps}=setup();await reportAction(input,deps);const owner={...deps,verify:async()=>({code:'owner',level:4})};await reportAction({...input,revision:1,mutationId:crypto.randomUUID(),body:'修正'},owner);assert.equal(rows[0].revision,2);assert.equal(rows[0].author_code,'test-a');});
test('retried create and edit do not create duplicates or increment revision again',async()=>{const{rows,deps}=setup();await reportAction(input,deps);assert.equal((await reportAction(input,deps)).replayed,true);const edited={...input,revision:1,mutationId:crypto.randomUUID(),body:'修正'};await reportAction(edited,deps);assert.equal((await reportAction(edited,deps)).replayed,true);assert.equal(rows.length,1);assert.equal(rows[0].revision,2);});
test('stale revision is rejected and preserves current body',async()=>{const{rows,deps}=setup();await reportAction(input,deps);await reportAction({...input,revision:1,mutationId:crypto.randomUUID(),body:'新版'},deps);await assert.rejects(reportAction({...input,revision:1,mutationId:crypto.randomUUID(),body:'旧版'},deps),e=>e.status===409);assert.equal(rows[0].body,'新版');});
test('validation rejects empty body, invalid dates and forged campus',()=>{for(const extra of [{body:' '},{eventDate:'2026-02-30'},{campus:'その他'},{externalUse:'yes'}])assert.throws(()=>validateReport({...input,...extra}));});
test('permission and campus restrictions are enforced before write',async()=>{const{rows,deps}=setup();deps.authorize=async()=>{throw Object.assign(new Error('Forbidden'),{status:403});};await assert.rejects(reportAction(input,deps),e=>e.status===403);assert.equal(rows.length,0);});
test('owner reader key only grants feed reading',async()=>{const{deps}=setup();await reportAction(input,deps);assert.equal((await reportAction({action:'ownerFeed',readerKey:'reader'},deps)).reports.length,1);await assert.rejects(reportAction({action:'ownerFeed',readerKey:'bad'},deps),e=>e.status===401);await assert.rejects(reportAction({...input,token:'',readerKey:'reader'},deps),e=>e.status===401);});
