import test from 'node:test';import assert from 'node:assert/strict';
import {reportAction} from '../supabase/functions/step-publicity-report-runtime-v1/report-core.mjs';
import {uploadAttachment,resolveAttachments,signedAttachment,cleanupAttachments,identifyFile,MAX_FILE_SIZE} from '../supabase/functions/step-publicity-report-runtime-v1/attachments-core.mjs';
const id='e597c70f-bc79-436f-87ed-762b6652d07e',aid='a9fed91a-a9fd-4265-9b16-7a65bc36fa64';
const pdf=new File(['%PDF-1.7\nexample'], '予定表.pdf',{type:'application/pdf'});
function setup(){const tables={step_publicity_reports:[],step_publicity_report_files:[]},ops=[];
 const actor={code:'test-a',level:1},deps={verify:async token=>{if(token!=='valid')throw Object.assign(new Error('Unauthorized'),{status:401});return actor;},authorize:async()=> 'all',verifyReader:async k=>{if(k!=='reader')throw Object.assign(new Error('Unauthorized'),{status:401});},storage:async(action,path,data)=>{ops.push({action,path,data});return 'https://storage.test/signed';},pg:async(path,opt={})=>{
 const u=new URL('https://test/'+path),params=u.searchParams,rows=tables[u.pathname.slice(1)];const matches=rows.filter(r=>[...params].every(([k,v])=>['select','limit','order','offset','on_conflict'].includes(k)||v==='is.null'?['select','limit','order','offset','on_conflict'].includes(k)||r[k]==null:v.startsWith('eq.')?String(r[k])===v.slice(3):v.startsWith('in.(')?v.slice(4,-1).split(',').includes(r[k]):true));
 if(opt.method==='POST'){const row=JSON.parse(opt.body);if(rows.some(r=>r.id===row.id))return [];rows.push(row);return[structuredClone(row)];}
 if(opt.method==='PATCH'){for(const r of matches)Object.assign(r,JSON.parse(opt.body));return structuredClone(matches);}
 if(opt.method==='DELETE'){tables[u.pathname.slice(1)]=rows.filter(r=>!matches.includes(r));return[];}return structuredClone(matches);
 }};
 deps.resolveAttachments=(ids,old,rid,a)=>resolveAttachments(ids,old,rid,a,deps.pg);deps.signedAttachment=(p,row)=>signedAttachment(p,row,deps);deps.cleanupAttachments=rid=>cleanupAttachments(rid,deps);
 return{tables,ops,deps,actor};}
const upload={reportId:id,attachmentId:aid,campus:'神領校',token:'valid',file:pdf};
const save={action:'save',id,revision:0,mutationId:'004008d8-e14e-4692-b123-d59f8a5c13bf',campus:'神領校',category:'行事予定',title:'予定',body:'来月の予定',token:'valid',attachmentIds:[aid]};
test('accepts real file signatures and rejects scripts disguised as photos',()=>{assert.equal(identifyFile(new Uint8Array([137,80,78,71,13,10,26,10])).mime,'image/png');assert.equal(identifyFile(new TextEncoder().encode('%PDF-1.7')).mime,'application/pdf');assert.throws(()=>identifyFile(new TextEncoder().encode('<html>photo.jpg</html>')),e=>e.status===400);});
test('upload retry stores once; metadata has no storage path or signed link',async()=>{const {tables,ops,deps}=setup();const r=await uploadAttachment(upload,deps);await uploadAttachment(upload,deps);assert.equal(ops.length,1);assert.equal(tables.step_publicity_report_files.length,1);assert.equal(r.attachment.name,'予定表.pdf');assert.equal(r.attachment.mimeType,'application/pdf');assert.equal(r.attachment.url,undefined);assert.equal(r.attachment.object_path,undefined);await assert.rejects(uploadAttachment({...upload,file:new File(['%PDF-1.7\ndifferent'],'別.pdf')},deps),e=>e.status===409);});
test('invalid size, authentication, ownership and campus reject uploads before storage',async()=>{const {tables,ops,deps}=setup();await assert.rejects(uploadAttachment({...upload,token:''},deps),e=>e.status===401);await assert.rejects(uploadAttachment({...upload,file:{size:MAX_FILE_SIZE+1}},deps),e=>e.status===413);tables.step_publicity_reports.push({id,author_code:'other',campus:'神領校'});await assert.rejects(uploadAttachment(upload,deps),e=>e.status===403);tables.step_publicity_reports=[];await assert.rejects(uploadAttachment(upload,{...deps,authorize:async()=>{throw Object.assign(new Error('campus'),{status:403});}}),e=>e.status===403);assert.equal(ops.length,0);});
test('report save retains file list; authorized preview signs only linked files',async()=>{const {tables,ops,deps}=setup();await uploadAttachment(upload,deps);const r=await reportAction(save,deps);assert.equal(r.report.attachments.length,1);assert.equal(r.report.attachments[0].id,aid);assert.equal((await reportAction({action:'attachmentUrl',id,attachmentId:aid,token:'valid'},deps)).url,'https://storage.test/signed');assert.equal(ops.at(-1).action,'sign');await assert.rejects(reportAction({action:'attachmentUrl',id,attachmentId:aid,token:'valid'},{...deps,verify:async()=>({code:'other',level:1})}),e=>e.status===403);await assert.rejects(reportAction({action:'ownerAttachmentUrl',id,attachmentId:aid,readerKey:'bad'},deps),e=>e.status===401);assert.equal((await reportAction({action:'ownerAttachmentUrl',id,attachmentId:aid,readerKey:'reader'},deps)).success,true);assert.equal(tables.step_publicity_reports[0].attachments.length,1);});
test('unlinked, missing, oversized lists and another report attachments cannot be saved or signed',async()=>{const {deps,tables}=setup();await uploadAttachment(upload,deps);await assert.rejects(resolveAttachments([aid,aid],null,id,{code:'test-a',level:1},deps.pg),e=>e.status===400);await assert.rejects(resolveAttachments([aid],null,crypto.randomUUID(),{code:'test-a',level:1},deps.pg),e=>e.status===400);await assert.rejects(resolveAttachments([aid],null,id,{code:'other',level:1},deps.pg),e=>e.status===400);await assert.rejects(signedAttachment({attachmentId:aid},{id,attachments:[]},deps),e=>e.status===404);tables.step_publicity_report_files[0].uploaded=false;await assert.rejects(reportAction(save,deps),e=>e.status===400);assert.equal(tables.step_publicity_reports.length,0);});
test('editing can remove attachments; deletion removes objects and old file metadata',async()=>{const {deps,tables,ops}=setup();await uploadAttachment(upload,deps);await reportAction(save,deps);await reportAction({...save,revision:1,mutationId:crypto.randomUUID(),attachmentIds:[]},deps);assert.equal(tables.step_publicity_reports[0].attachments.length,0);await assert.rejects(reportAction({action:'attachmentUrl',id,attachmentId:aid,token:'valid'},deps),e=>e.status===404);await reportAction({action:'delete',id,revision:2,mutationId:crypto.randomUUID(),token:'valid'},deps);assert.equal(tables.step_publicity_report_files.length,0);assert.equal(ops.at(-1).action,'remove');await assert.rejects(reportAction({action:'ownerAttachmentUrl',id,attachmentId:aid,readerKey:'reader'},deps),e=>e.status===404);});
